// Generated by spanreed desktop-contracts; do not edit.
import type { MigrationSessionView } from '@fabrials/ui';

export type ResetNotificationSettings = { resetExpiry: boolean, };

export type RoutingPolicy = { provider: string, autosteer: boolean, exhausted_pct: number, mode: string, };

export type PoolAccount = { alias: string, plan: string | null, used_pct: number | null, resets_at: string | null, exhausted: boolean, role: string, };

export type ProviderPool = { provider: string, route: string, autosteer: boolean, accounts: Array<PoolAccount>, };

export type RoutingLimits = { mode: string, exhausted_pct: number, providers: Array<ProviderPool>, };

export type RoutingSnapshot = { policies: Array<RoutingPolicy>, limits: RoutingLimits, };

export type DeviceView = { verificationUri: string, userCode: string, expiresIn: number, interval: number, };

export type Progress = { "state": "pending", retryAfterSecs: number, } | { "state": "connected" };

export type LoginView = { id: string, alias: string, provider: string, device: DeviceView, };

export type AccountSummary = { id: string, provider: string, alias: string, generation: string | null, active: boolean, plan_label: string | null, };

export type AccountsView = { accounts: Array<AccountSummary>, };

export type Detection = { id: string, name: string, detected: boolean, };

export type ModelCatalog = { accountId: string, observedAtMs: number, models: Array<string>, };

export type ProxyState = "running" | "stopping" | "stopped";

export type Status = { state: ProxyState, bind: string, error: string | null, };

export type ConfigurationClient = "opencode" | "grok";

export type Operation = "create" | "update" | "remove";

export type Preview = { warnings: Array<string>, id: string, path: string, providerId: string, addition: unknown, client: ConfigurationClient, operation: Operation, };

export type SavedSession = { id: string, origin: string, view: MigrationSessionView | null, imported: Array<string> | null, };
