// Generated by spanreed desktop-contracts; do not edit.
import type { MigrationSessionView, ProviderOutput, HistorySample, UsageRecord } from '@fabrials/ui';

export type PublicationStatus = { lastSharedDay: string | null, due: boolean, schedule: string, };

export type SyncSettings = { sources: Array<string>, };

export type SessionMoveView = { id: string, state: string, alias: string, source_path: string, config_path: string, endpoint: string, account_id: string | null, };

export type HostedClientReview = { id: string, client: string, path: string, account_id: string, model: string, endpoint: string, };

export type SyncStatus = { lastSuccessMs: number | null, uploaded: number, downloaded: number, error: string | null, };

export type PrivateEvent = { "kind": "quota", at_ms: number, output: ProviderOutput, } | { "kind": "history", sample: HistorySample, } | { "kind": "request", record: UsageRecord, };

export type PrivateObservation = { source: string, event: PrivateEvent, };

export type PrivateStoredObservation = { cursor: number, device: string, observation: PrivateObservation, };

export type PrivatePage = { observations: Array<PrivateStoredObservation>, next_cursor: number, has_more: boolean, };

export type PrivateRecentPage = { observations: Array<PrivateStoredObservation>, before: number | null, has_more: boolean, };

export type RemoteOperation = "importCodexSession" | "codexSessionStatus" | "cancelCodexSession" | "linkCodexSource" | "syncCapabilities" | "putLocalUsage" | "pushSync" | "pullSync" | "recentSync" | "dashboard" | "addAccount" | "probeAccount" | "deleteAccount" | "activateAccount" | "setQuota" | "setAutosteer" | "createKey" | "revokeKey" | "updateKey" | "rotateKey" | "beginGrok" | "pollGrok" | "cancelGrok" | "beginCodex" | "reauthorizeCodex" | "pollCodex" | "cancelCodex" | "beginNous" | "reauthorizeNous" | "pollNous" | "cancelNous" | "migrationSessions" | "migrationCandidates" | "beginMigration" | "migrationStatus" | "approveMigration" | "cancelMigration" | "forgetMigration" | "migrationAuthorizations";

export type FabrialsIdentity = { id: string, username: string, };

export type LinkView = { "state": "disconnected" } | { "state": "declined" } | { "state": "expired" } | { "state": "pending", id: string, userCode: string, verificationUri: string, expiresAtMs: number, retryAfterSecs: number, } | { "state": "linked", user: FabrialsIdentity, };

export type ResetNotificationSettings = { resetExpiry: boolean, };

export type RoutingPolicy = { provider: string, autosteer: boolean, exhausted_pct: number, mode: string, };

export type PoolAccount = { alias: string, plan: string | null, used_pct: number | null, resets_at: string | null, exhausted: boolean, role: string, };

export type ProviderPool = { provider: string, route: string, autosteer: boolean, accounts: Array<PoolAccount>, };

export type RoutingLimits = { mode: string, exhausted_pct: number, providers: Array<ProviderPool>, };

export type RoutingSnapshot = { policies: Array<RoutingPolicy>, limits: RoutingLimits, };

export type DeviceView = { verificationUri: string, userCode: string, expiresIn: number, interval: number, };

export type Progress = { "state": "pending", retryAfterSecs: number, } | { "state": "connected" };

export type LoginView = { id: string, alias: string, provider: string, device: DeviceView, };

export type AccountSummary = { id: string, provider: string, alias: string, generation: string | null, active: boolean, plan_label: string | null, };

export type AccountsView = { accounts: Array<AccountSummary>, };

export type Detection = { id: string, name: string, detected: boolean, };

export type ModelCatalog = { accountId: string, observedAtMs: number, models: Array<string>, };

export type ProxyState = "running" | "stopping" | "stopped";

export type Status = { state: ProxyState, bind: string, error: string | null, };

export type ConfigurationClient = "opencode" | "grok";

export type Operation = "create" | "update" | "remove";

export type Preview = { warnings: Array<string>, id: string, path: string, providerId: string, addition: unknown, client: ConfigurationClient, operation: Operation, };

export type SavedSession = { id: string, origin: string, view: MigrationSessionView | null, imported: Array<string> | null, };
