// Generated by ai-relay --print-dashboard-contracts; do not edit.
import type { Observation, CreditBalance, ResetCredits as ResetInventory, MigrationSessionView, MigrationDirection, MigrationCandidate, SynchronizedAccount, ProviderOutput } from '@fabrials/ui';

export type MutationSuccess = { ok: boolean, };

export type IssuedKey = { ok: boolean, key: string, prefix: string, };

export type KeyTarget = { key_hash: string, };

export type ManualQuotaResult = { ok: boolean, id: string, cleared: boolean, } | { ok: boolean, id: string, used_pct: number | null, };

export type PoolConfigUpdated = { ok: boolean, config: FabrialsPoolConfig, };

export type MigrationCandidates = { accounts: Array<MigrationCandidate>, };

export type AutosteerRequest = { provider: string, on: boolean, };

export type AutosteerUpdated = { provider: string, autosteer: boolean, exhausted_pct: number, mode: string, };

export type GrokDeviceTarget = { state: string, };

export type GrokAuthorizationRequest = { alias: string, reauthorize?: boolean, newOnly?: boolean, migrationId?: string, sourceId?: string, };

export type NousAuthorizationRequest = { alias: string, migrationId?: string, sourceId?: string, };

export type NousDeviceTarget = { id: string, };

export type KeyPolicyRequest = { key_hash?: string, pool_policy?: boolean, name?: string | null, budget_usd?: QuotaAmount | null, budget_period?: string, allow_providers?: PolicyScopes | null, allow_accounts?: PolicyScopes | null, allow_models?: PolicyScopes | null, allow_routes?: PolicyScopes | null, allow_kinds?: PolicyScopes | null, };

export type PolicyScopes = Array<string> | string;

export type ConnectAccountRequest = { provider: string, alias: string, api_key: string, active: boolean | null, plan: string | null, };

export type ConnectedAccount = { ok: boolean, id: string, provider: string, alias: string, };

export type AccountTarget = { provider: string, alias: string, };

export type QuotaAmount = number | string;

export type ManualQuotaRequest = { provider: string, alias: string, clear?: boolean, credits_remaining?: QuotaAmount, credits_grant?: QuotaAmount, resets_at?: string, plan?: string, };

export type MigrationSessions = { sessions: Array<MigrationSessionView>, };

export type MigrationInvitationRequest = { direction: MigrationDirection, };

export type MigrationSessionRequest = { id: string, };

export type MigrationApprovalRequest = { id: string, revision: string, };

export type DeviceView = { verificationUri: string, userCode: string, expiresIn: number, interval: number, };

export type LoginView = { id: string, device: DeviceView, };

export type Progress = { "state": "pending", retryAfterSecs: number, } | { "state": "connected", accountId: string, };

export type GrokDeviceStart = { state: string, verification_uri: string, user_code: string, expires_in: number, interval: number, };

export type LinkedAccount = { id: string, };

export type GrokDeviceProgress = { "status": "pending", retry_after_secs: number, } | { "status": "linked", account: LinkedAccount, };

export type DashboardPayload = { generated_at_ms: number, usage_truncated: boolean, session: SessionView, relay: RelayView, summary: Summary, accounts: Array<AccountView>, synchronized_accounts: Array<SynchronizedAccount>, keys: Array<KeyView>, steering: Array<SteerProviderView>, catalog: Array<CatalogModelView>, connectors: Array<ConnectorView>, fab_pool: FabrialsPoolConfig | null, };

export type SessionView = { owner: string, username: string | null, };

export type RelayView = { id: string, version: string, mode: string, capabilities: Array<string>, endpoints: Array<RelayEndpoint>, };

export type CatalogStateView = { models: Array<string>, probed_at_ms: number, ok: boolean, detail: string | null, identity: string | null, };

export type AccountView = { usage_output: ProviderOutput | null, reset_inventory: Observation<ResetInventory> | null, balance: Observation<CreditBalance> | null, id: string, provider: string, alias: string, label: string, active: boolean, plan: string | null, used_pct: number | null, resets_at: string | null, has_secret: boolean, quota_detail: string | null, catalog: CatalogStateView | null, email: string | null, auth_type: string, needs_reauth: boolean, };

export type KeyPolicyView = { pool_policy: boolean, name: string, budget_usd: number | null, budget_period: string, allow_providers: Array<string>, allow_accounts: Array<string>, allow_models: Array<string>, allow_routes: Array<string>, allow_kinds: Array<string>, };

export type KeyView = { key_hash: string, prefix: string | null, enabled: boolean, spent_usd: number, policy: KeyPolicyView, };

export type SteerQueueView = { id: string, alias: string, plan: string | null, used_pct: number | null, resets_at: string | null, active: boolean, exhausted: boolean, score: number, factors: string, };

export type SteerProviderView = { provider: string, route: string, enabled: boolean, mode: string, exhausted_pct: number, queue: Array<SteerQueueView>, };

export type CatalogModelView = { provider: string, model: string, account_alias: string, probed_at_ms: number, };

export type ConnectorView = { id: string, name: string, machine_kind: string, transport: string, status: string, version: string | null, latest_version: string | null, last_seen_at_ms: number | null, endpoint: string | null, providers: Array<string>, is_default: boolean, };

export type Totals = { requests: number, input_tokens: number, output_tokens: number, cached_input_tokens: number, usd: number, };

export type AccountRow = { id: string, alias: string, provider: string, plan: string | null, used_pct: number | null, active: boolean, requests: number, tokens: number, usd: number, };

export type ModelRow = { model: string, requests: number, tokens: number, usd: number, };

export type RecentHop = { ts_ms: number, account_id: string | null, model: string | null, kind: string | null, input_tokens: number, output_tokens: number, duration_ms: number | null, status: number | null, usd: number, };

export type Summary = { days: number, today: Totals, window: Totals, accounts: Array<AccountRow>, models: Array<ModelRow>, recent: Array<RecentHop>, };

export type RelayEndpoint = { key: string, label: string, http_url: string, websocket_url: string | null, reachability: string, available: boolean, is_default: boolean, };

export type FabrialsPoolConfig = { enabled: boolean, daily_budget_usd: number, default_model: string, allowed_models: Array<string>, reasoning_mode: ReasoningMode, max_output_tokens: number | null, rate_limit_rpm: number | null, };

export type ReasoningMode = "force_low" | "force_medium" | "force_high" | "allow_custom";
