//! Native presentation DTOs stay in the host; shared domain DTOs are imported.
use ts_rs::{Config, TS};

pub fn typescript() -> String {
    let config = Config::new().with_large_int("number");
    let declarations = [
        crate::app::sharing::PublicationStatus::decl(&config),
        crate::app::sync::SyncSettings::decl(&config),
        crate::app::clients::SessionMoveView::decl(&config),
        crate::app::clients::HostedClientReview::decl(&config),
        crate::app::sync::SyncStatus::decl(&config),
        fabrials_types::private_sync::PrivateEvent::decl(&config),
        fabrials_types::private_sync::PrivateObservation::decl(&config),
        fabrials_types::private_sync::PrivateStoredObservation::decl(&config),
        fabrials_types::private_sync::PrivatePage::decl(&config),
        fabrials_types::private_sync::PrivateRecentPage::decl(&config),
        crate::app::fabrials::RemoteOperation::decl(&config),
        crate::app::fabrials::FabrialsIdentity::decl(&config),
        crate::app::fabrials::LinkView::decl(&config),
        crate::app::notifications::Settings::decl(&config),
        crate::app::routing::RoutingPolicy::decl(&config),
        crate::app::routing::PoolAccount::decl(&config),
        crate::app::routing::ProviderPool::decl(&config),
        crate::app::routing::RoutingLimits::decl(&config),
        crate::app::routing::RoutingSnapshot::decl(&config),
        fabrials_providers::device_flow::DeviceView::decl(&config),
        fabrials_providers::device_flow::Progress::decl(&config),
        crate::app::accounts::LoginView::decl(&config),
        crate::app::accounts::AccountSummary::decl(&config),
        crate::app::accounts::AccountsView::decl(&config),
        crate::app::usage::Detection::decl(&config),
        crate::app::accounts::ModelCatalog::decl(&config),
        crate::app::proxy::ProxyState::decl(&config),
        crate::app::proxy::Status::decl(&config),
        crate::app::agent::AgentStatus::decl(&config),
        crate::app::clients::ConfigurationClient::decl(&config),
        crate::app::clients::Operation::decl(&config),
        crate::app::clients::Preview::decl(&config),
        crate::app::migration::SavedSession::decl(&config),
    ];
    format!(
        "// Generated by spanreed desktop-contracts; do not edit.\nimport type {{ MigrationSessionView, ProviderOutput, HistorySample, UsageRecord }} from '@fabrials/ai-ui';\n\n{}\n",
        declarations
            .map(|value| format!("export {value}"))
            .join("\n\n")
    )
}

#[cfg(test)]
mod tests {
    #[test]
    fn shared_type_contracts_match_the_checked_in_bindings() {
        let generated = fabrials_types::contracts::typescript();
        assert_eq!(
            generated,
            include_str!(
                "../../../vendor/fabrials-libs/crates/fabrials-types/bindings/contracts.ts"
            )
        );
    }

    #[test]
    fn renderer_contracts_match_native_dtos() {
        assert_eq!(
            super::typescript(),
            include_str!("../../../desktop/src/contracts.ts"),
            "Regenerate desktop/src/contracts.ts with the desktop-contracts example"
        );
    }
}
