//! Native presentation DTOs stay in the host; shared domain DTOs are imported.
use ts_rs::{Config, TS};

pub fn typescript() -> String {
    let config = Config::new().with_large_int("number");
    let declarations = [
        crate::app::sharing::PublicationStatus::decl(&config),
        crate::sync::SyncSettings::decl(&config),
        crate::codex_session_move::SessionMoveView::decl(&config),
        crate::hosted_client_configuration::HostedClientReview::decl(&config),
        crate::sync::SyncStatus::decl(&config),
        fabrials_types::private_sync::PrivateEvent::decl(&config),
        fabrials_types::private_sync::PrivateObservation::decl(&config),
        fabrials_types::private_sync::PrivateStoredObservation::decl(&config),
        fabrials_types::private_sync::PrivatePage::decl(&config),
        fabrials_types::private_sync::PrivateRecentPage::decl(&config),
        crate::remote_workspace::RemoteOperation::decl(&config),
        crate::fabrials_login::FabrialsIdentity::decl(&config),
        crate::fabrials_login::LinkView::decl(&config),
        crate::notifications::Settings::decl(&config),
        crate::local_control::RoutingPolicy::decl(&config),
        crate::local_control::PoolAccount::decl(&config),
        crate::local_control::ProviderPool::decl(&config),
        crate::local_control::RoutingLimits::decl(&config),
        crate::app::routing::RoutingSnapshot::decl(&config),
        fabrials_providers::device_flow::DeviceView::decl(&config),
        fabrials_providers::device_flow::Progress::decl(&config),
        crate::account_login::LoginView::decl(&config),
        crate::app::accounts::AccountSummary::decl(&config),
        crate::app::accounts::AccountsView::decl(&config),
        crate::app::usage::Detection::decl(&config),
        crate::app::accounts::ModelCatalog::decl(&config),
        crate::desktop_runtime::ProxyState::decl(&config),
        crate::desktop_runtime::Status::decl(&config),
        crate::client_configuration::ConfigurationClient::decl(&config),
        crate::client_configuration::Operation::decl(&config),
        crate::client_configuration::Preview::decl(&config),
        crate::migration::session::SavedSession::decl(&config),
    ];
    format!(
        "// Generated by spanreed desktop-contracts; do not edit.\nimport type {{ MigrationSessionView, ProviderOutput, HistorySample, UsageRecord }} from '@fabrials/ai-ui';\n\n{}\n",
        declarations
            .map(|value| format!("export {value}"))
            .join("\n\n")
    )
}

#[cfg(test)]
mod tests {
    #[test]
    fn shared_type_contracts_match_the_checked_in_bindings() {
        let generated = fabrials_types::contracts::typescript();
        assert_eq!(
            generated,
            include_str!("../vendor/fabrials-libs/crates/fabrials-types/bindings/contracts.ts")
        );
    }

    #[test]
    fn renderer_contracts_match_native_dtos() {
        assert_eq!(
            super::typescript(),
            include_str!("../desktop/src/contracts.ts"),
            "Regenerate desktop/src/contracts.ts with the desktop-contracts example"
        );
    }
}
